### ISSUE TITLE
beancount 2.3.1 版本下会报错

### ISSUE THREAD

**Issue by dofine** [mckelvin/beancount-boilerplate-cn#4]
> AttributeError: module 'beancount.reports.holdings_reports' has no attribute 'get_assets_holdings'

怀疑是跟 2.3.1 版本移除了 bean-report 有关？回退到2.3.0正常。

**Comment by mckelvin** [comment]
Fixed in https://github.com/mckelvin/beancount-boilerplate-cn/commit/f250b25c2a05b6cf922b59a598ffb4fda4dead8d#diff-ada348c5f9b428ff47fcacaab9e8a59866b86f39dcaa40e98a9e84a040cb2028L22
